# Generated by Django 2.1.2 on 2018-11-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20181114_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrecord',
            name='lesson_date',
            field=models.DateField(verbose_name='受講日'),
        ),
    ]
