# Generated by Django 2.1.2 on 2018-11-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20181114_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrecord',
            name='attending_time',
            field=models.IntegerField(default=1, verbose_name='受講時間'),
        ),
    ]
